export default function () {
  return {
    // items: {
    columns: [
      {
        name: "account_name",
        align: "left",
        label: "Account Name",
        field: "account_name",
        sortable: true,
      },
      {
        name: "phone",
        align: "left",
        label: "Phone No.",
        field: "phone",
        sortable: true,
      },
      {
        name: "email",
        align: "left",
        label: "Email",
        field: "email",
        sortable: true,
      },
      {
        name: "city_id",
        align: "left",
        label: "City",
        field: (row) => row?.city?.city_name,
        sortable: true,
      },
      {
        name: "address_1",
        align: "left",
        label: "Address 1",
        field: "address_1",
        sortable: true,
      },
      {
        name: "address_2",
        align: "left",
        label: "Address 2",
        field: "address_2",
        sortable: true,
      },
      {
        name: "postcode",
        align: "left",
        label: "PostCode",
        field: "postcode",
        sortable: true,
      },
      {
        name: "branch_id",
        align: "left",
        label: "Branch Name",
        field: (row) => row?.branch?.name,
        sortable: true,
      },
      {
        name: "adhaar_media_id",
        align: "left",
        label: "Adhaar",
        field: "adhaar_media_id",
        sortable: true,
      },
      {
        name: "type",
        align: "left",
        label: "Type",
        field: "type",
        sortable: true,
      },
      {
        name: "account_no",
        align: "left",
        label: "Account No.",
        field: "account_no",
        sortable: true,
      },
      {
        name: "ifsc",
        align: "left",
        label: "IFSC",
        field: "ifsc",
        sortable: true,
      },
      {
        name: "bank_branch",
        align: "left",
        label: "Bank Branch",
        field: "bank_branch",
        sortable: true,
      },
      { name: "actions", align: "right", label: "Actions" },
    ],
    visibleColumns: ["name"],
    data: [],
    pagination: {
      sortBy: "",
      descending: false,
      page: 1,
      direction: null,
      rowsPerPage: 10,
      totalRecords: 0,
    },
    filter: {
      search: "",
      trashed: false,
    },
    lastUpdated: "",
    // },
    newItem: {
      account_name: null,
      type: "",
      branch_id: null,
      opening_balance: null,
      balance_type: "",
    },
    editItem: {
      account_name: null,
      phone: null,
      email: "",
      city_id: null,
      address_1: "",
      address_2: "",
      postcode: null,
      branch_id: "",
      adhaar_media_id: "",
      type: "",
      account_no: "",
      ifsc: "",
      bank_branch: "",
    },
    ViewMoreDetails: {
      name: "",
      code: "",
      address_1: "",
      address_2: "",
      postcode: "",
      city_id: "",
    },
    modals: {
      createItem: false,
      editItem: false,
      ViewMoreDetails: false,
    },
  };
}
